package models

type Conf struct {
	ConfVersion                            int           `json:"ConfVersion"`
	Id                                     string        `json:"Id"`
	MasterQuorum                           bool          `json:"MasterQuorum"`
	FullSyncHTTPListenPort                 int           `json:"FullSyncHTTPListenPort"`
	IncrSyncHTTPListenPort                 int           `json:"IncrSyncHTTPListenPort"`
	SystemProfilePort                      int           `json:"SystemProfilePort"`
	LogLevel                               string        `json:"LogLevel"`
	LogDirectory                           string        `json:"LogDirectory"`
	LogFileName                            string        `json:"LogFileName"`
	LogFlush                               bool          `json:"LogFlush"`
	SyncMode                               string        `json:"SyncMode"`
	MongoUrls                              []string      `json:"MongoUrls"`
	MongoCsUrl                             string        `json:"MongoCsUrl"`
	MongoSUrl                              string        `json:"MongoSUrl"`
	MongoSslRootCaFile                     string        `json:"MongoSslRootCaFile"`
	MongoSslClientCaFile                   string        `json:"MongoSslClientCaFile"`
	MongoConnectMode                       string        `json:"MongoConnectMode"`
	Tunnel                                 string        `json:"Tunnel"`
	TunnelAddress                          []string      `json:"TunnelAddress"`
	TunnelMessage                          string        `json:"TunnelMessage"`
	TunnelKafkaPartitionNumber             int           `json:"TunnelKafkaPartitionNumber"`
	TunnelJsonFormat                       string        `json:"TunnelJsonFormat"`
	TunnelMongoSslRootCaFile               string        `json:"TunnelMongoSslRootCaFile"`
	FilterNamespaceBlack                   []interface{} `json:"FilterNamespaceBlack"`
	FilterNamespaceWhite                   []interface{} `json:"FilterNamespaceWhite"`
	FilterPassSpecialDb                    []interface{} `json:"FilterPassSpecialDb"`
	FilterDDLEnable                        bool          `json:"FilterDDLEnable"`
	FilterOplogGids                        bool          `json:"FilterOplogGids"`
	CheckpointStorageUrl                   string        `json:"CheckpointStorageUrl"`
	CheckpointStorageDb                    string        `json:"CheckpointStorageDb"`
	CheckpointStorageCollection            string        `json:"CheckpointStorageCollection"`
	CheckpointStorageUrlMongoSslRootCaFile string        `json:"CheckpointStorageUrlMongoSslRootCaFile"`
	CheckpointStartPosition                int           `json:"CheckpointStartPosition"`
	TransformNamespace                     []interface{} `json:"TransformNamespace"`
	SpecialSourceDBFlag                    string        `json:"SpecialSourceDBFlag"`
	SkipNSShareKeyVerify                   interface{}   `json:"SkipNSShareKeyVerify"`
	FullSyncReaderCollectionParallel       int           `json:"FullSyncReaderCollectionParallel"`
	FullSyncReaderWriteDocumentParallel    int           `json:"FullSyncReaderWriteDocumentParallel"`
	FullSyncReaderDocumentBatchSize        int           `json:"FullSyncReaderDocumentBatchSize"`
	FullSyncReaderFetchBatchSize           int           `json:"FullSyncReaderFetchBatchSize"`
	FullSyncReaderParallelThread           int           `json:"FullSyncReaderParallelThread"`
	FullSyncReaderParallelIndex            string        `json:"FullSyncReaderParallelIndex"`
	FullSyncCollectionDrop                 bool          `json:"FullSyncCollectionDrop"`
	FullSyncCreateIndex                    string        `json:"FullSyncCreateIndex"`
	FullSyncReaderOplogStoreDisk           bool          `json:"FullSyncReaderOplogStoreDisk"`
	FullSyncReaderOplogStoreDiskMaxSize    int           `json:"FullSyncReaderOplogStoreDiskMaxSize"`
	FullSyncExecutorInsertOnDupUpdate      bool          `json:"FullSyncExecutorInsertOnDupUpdate"`
	FullSyncExecutorFilterOrphanDocument   bool          `json:"FullSyncExecutorFilterOrphanDocument"`
	FullSyncExecutorMajorityEnable         bool          `json:"FullSyncExecutorMajorityEnable"`
	IncrSyncMongoFetchMethod               string        `json:"IncrSyncMongoFetchMethod"`
	IncrSyncChangeStreamWatchFullDocument  bool          `json:"IncrSyncChangeStreamWatchFullDocument"`
	IncrSyncReaderFetchBatchSize           int           `json:"IncrSyncReaderFetchBatchSize"`
	IncrSyncOplogGIDS                      []interface{} `json:"IncrSyncOplogGIDS"`
	IncrSyncShardKey                       string        `json:"IncrSyncShardKey"`
	IncrSyncShardByObjectIdWhiteList       []interface{} `json:"IncrSyncShardByObjectIdWhiteList"`
	IncrSyncWorker                         int           `json:"IncrSyncWorker"`
	IncrSyncTunnelWriteThread              int           `json:"IncrSyncTunnelWriteThread"`
	IncrSyncTargetDelay                    int           `json:"IncrSyncTargetDelay"`
	IncrSyncWorkerBatchQueueSize           int           `json:"IncrSyncWorkerBatchQueueSize"`
	IncrSyncAdaptiveBatchingMaxSize        int           `json:"IncrSyncAdaptiveBatchingMaxSize"`
	IncrSyncFetcherBufferCapacity          int           `json:"IncrSyncFetcherBufferCapacity"`
	IncrSyncExecutorUpsert                 bool          `json:"IncrSyncExecutorUpsert"`
	IncrSyncExecutorInsertOnDupUpdate      bool          `json:"IncrSyncExecutorInsertOnDupUpdate"`
	IncrSyncConflictWriteTo                string        `json:"IncrSyncConflictWriteTo"`
	IncrSyncExecutorMajorityEnable         bool          `json:"IncrSyncExecutorMajorityEnable"`
	CheckpointStorage                      string        `json:"CheckpointStorage"`
	CheckpointInterval                     int           `json:"CheckpointInterval"`
	FullSyncExecutorDebug                  bool          `json:"FullSyncExecutorDebug"`
	IncrSyncDBRef                          bool          `json:"IncrSyncDBRef"`
	IncrSyncExecutor                       int           `json:"IncrSyncExecutor"`
	IncrSyncExecutorDebug                  bool          `json:"IncrSyncExecutorDebug"`
	IncrSyncReaderDebug                    string        `json:"IncrSyncReaderDebug"`
	IncrSyncCollisionEnable                bool          `json:"IncrSyncCollisionEnable"`
	IncrSyncReaderBufferTime               int           `json:"IncrSyncReaderBufferTime"`
	IncrSyncWorkerOplogCompressor          string        `json:"IncrSyncWorkerOplogCompressor"`
	IncrSyncTunnelKafkaDebug               string        `json:"IncrSyncTunnelKafkaDebug"`
	Version                                string        `json:"Version"`
	SourceDBVersion                        string        `json:"SourceDBVersion"`
	TargetDBVersion                        string        `json:"TargetDBVersion"`
	IncrSyncTunnel                         string        `json:"IncrSyncTunnel"`
	IncrSyncTunnelAddress                  interface{}   `json:"IncrSyncTunnelAddress"`
	IncrSyncTunnelMessage                  string        `json:"IncrSyncTunnelMessage"`
	HTTPListenPort                         int           `json:"HTTPListenPort"`
	SystemProfile                          int           `json:"SystemProfile"`
}
